export const dict = {
  id: {
    sidebar: {
      dashboard: "Dashboard",
      profile: "Profil",
      subjects: "Mata Pelajaran",
      classes: "Kelas",
      students: "Siswa",
      attendance: "Absensi",
      gradebook: "Buku Nilai",
      notes: "Catatan",
      materials: "Materi Ajar",
      journals: "Jurnal Guru",
      evaluations: "Soal Evaluasi",
      calendar: "Kalender",
      settings: "Pengaturan (Backup)",
      about: "Tentang / Bantuan",
      offlineMode: "Mode Offline Aktif",
      offlineDesc: "Aplikasi berjalan offline di browser Anda",
      shortcut: "Pintasan",
      expandNav: "Perbesar Navigasi",
      collapseNav: "Sembunyikan Navigasi",
      openNav: "Buka Navigasi"
    },
    topbar: {
      dashboard: "Dashboard Overview"
    },
    pwaUpdate: {
      title: "Pembaruan EduPlanner tersedia",
      description: "Simpan pekerjaan Anda terlebih dahulu. Pembaruan hanya diterapkan dan halaman dimuat ulang setelah Anda memilih Perbarui sekarang.",
      later: "Nanti",
      updateNow: "Perbarui sekarang",
      updating: "Memperbarui...",
      error: "Pembaruan gagal diterapkan. Periksa koneksi Anda lalu coba lagi."
    },
    dashboard: {
      exportBtn: "Export Data",
      exporting: "Mengekspor...",
      studentData: "TOTAL DATA SISWA",
      registered: "TERDAFTAR",
      noStudentData: "Belum ada data siswa",
      studentScattered: "Siswa tersebar di {{totalClasses}} Kelas",
      manageStudents: "Kelola Siswa",
      quickAccess: "AKSES CEPAT PENGISIAN",
      main: "UTAMA",
      others: "LAINNYA",
      fillAttendance: "Isi Absensi Kelas",
      inputGrades: "Input Nilai Harian",
      viewSchedule: "Jadwal Mengajar",
      activeClasses: "KELAS AKTIF",
      totalClassesPrompt: "Total kelas yang",
      yourTeach: "Anda ampu",
      recentNotes: "CATATAN TERAKHIR",
      seeAllDesc: "Lihat semua catatan \u2192",
      noNotes: "Belum ada catatan.",
      tasksPending: "Tugas Tertunda",
      localStorageStr: "Penyimpanan Lokal",
      browserIndexedDbStr: "Browser IndexedDB",
      upcomingClassesToday: "Jadwal Hari Ini",
      noUpcomingClasses: "Tidak ada jadwal mengajar hari ini. Selamat beristirahat! 🌟",
      teachingHoursTitle: "Statistik Jam Mengajar",
      teachingHoursDesc: "Waktu mengajar Anda yang tercatat",
      sixMonths: "6 Bulan",
      twelveMonths: "12 Bulan",
      hours: "Jam",
      minutes: "Menit",
      ongoing: "Sedang Berlangsung",
      upcoming: "Akan Datang",
      finished: "Selesai",
      openClass: "Buka Kelas",
      totalHours: "Total Jam",
      totalSessions: "Total Sesi",
      sessionsUnit: "Sesi"
    },
    profilePage: {
      title: "Profil Pengajar",
      desc: "Kelola identitas pengajar yang akan tampil pada laporan.",
      detailTitle: "Detail Profil",
      detailDesc: "Informasi ini ditambahkan ke tampilan rapor atau slip laporan.",
      fullName: "Nama Lengkap (beserta gelar)",
      fullNamePlaceholder: "Contoh: Budi Santoso, M.Pd.",
      school: "Asal Sekolah",
      schoolPlaceholder: "Contoh: SMA Negeri 1 Jakarta",
      role: "Jabatan / Peran",
      rolePlaceholder: "Contoh: Wali Kelas / Guru Mapel",
      email: "Email",
      emailPlaceholder: "contoh: nama@sekolah.sch.id",
      avatar: "URL Avatar",
      avatarPlaceholder: "URL gambar profil (opsional)",
      saveSuccess: "Profil berhasil disimpan",
      saveError: "Gagal menyimpan profil",
      errorEmptyName: "Nama lengkap wajib diisi"
    },
    subjectsPage: {
      title: "Mata Pelajaran",
      desc: "Kelola daftar mata pelajaran yang Anda ampu.",
      addSubject: "Tambah Mata Pelajaran",
      addDialogTitle: "Tambah Mata Pelajaran Baru",
      addDialogDesc: "Masukkan nama mata pelajaran beserta deskripsi opsional.",
      nameLabel: "Nama Mata Pelajaran (contoh: Matematika Wajib)",
      namePlaceholder: "Nama Mata Pelajaran...",
      descLabel: "Deskripsi (opsional)",
      descPlaceholder: "Deskripsi...",
      emptyTitle: "Belum ada mata pelajaran",
      emptyDesc: "Mulai dengan menambahkan mata pelajaran agar dapat menautkannya saat memasukkan nilai atau absensi.",
      addFirstBtn: "Tambah Mata Pelajaran Pertama",
      noDesc: "Tidak ada deskripsi",
      errorEmpty: "Nama mata pelajaran tidak boleh kosong",
      successAdd: "Mata pelajaran berhasil dibuat",
      errorAdd: "Gagal membuat mata pelajaran",
      confirmDelete: "Hapus mata pelajaran ini? Nilai, presensi, tugas, catatan, dan jadwal berulang akan dipertahankan tanpa label mata pelajaran. Riwayat mengajar yang tertaut akan dihapus.",
      successDelete: "Mata pelajaran dihapus",
      manageStudents: "Kelola Siswa",
      studentsCount: "{{count}} siswa",
      assignClass: "Assign / Tambah Kelas",
      selectClass: "Pilih Kelas",
      btnAssign: "Assign Kelas",
      enrolledStudents: "Siswa Terdaftar",
      emptyEnrolled: "Belum ada siswa yang terdaftar di mata pelajaran ini.",
      removeClass: "Keluarkan",
      btnSaveEnrolled: "Tutup",
      successAssign: "Seluruh siswa kelas berhasil ditambahkan",
      successRemoveStudent: "Siswa dikeluarkan dari mata pelajaran",
      tooltipManageStudents: "Kelola Siswa Terdaftar"
    },
    classesPage: {
      title: "Kelas Saya",
      desc: "Kelola daftar kelas dan siswa yang Anda ajar.",
      addClass: "Tambah Kelas",
      addDialogTitle: "Tambah Kelas Baru",
      addDialogDesc: "Masukkan nama kelas beserta deskripsi opsional.",
      nameLabel: "Nama Kelas (contoh: XII IPA 1)",
      namePlaceholder: "Nama Kelas...",
      descLabel: "Deskripsi (opsional)",
      descPlaceholder: "Tahun Ajaran 2024/2025",
      emptyTitle: "Belum ada kelas",
      emptyDesc: "Mulai dengan menambahkan kelas pertama Anda untuk mengelola presensi dan nilai.",
      addFirstBtn: "Tambah Kelas Pertama",
      noDesc: "Tidak ada deskripsi",
      viewStudents: "Lihat Siswa",
      deleteTooltip: "Hapus Kelas",
      errorEmpty: "Nama kelas tidak boleh kosong",
      successAdd: "Kelas berhasil dibuat",
      errorAdd: "Gagal membuat kelas",
      editClass: "Edit Kelas",
      editDialogDesc: "Ubah nama atau deskripsi kelas ini.",
      successUpdate: "Kelas berhasil diperbarui",
      errorUpdate: "Gagal memperbarui kelas",
      confirmDelete: "Hapus kelas ini secara permanen beserta seluruh siswa, presensi, nilai, materi, tugas, jadwal, dan riwayat mengajarnya?",
      successDelete: "Kelas dihapus"
    },
    classDetail: {
      notFound: "Kelas tidak ditemukan.",
      management: "Manajemen kelas dan log mengajar",
      tabStudents: "Daftar Siswa",
      tabLog: "Log Mengajar",
      tabMaterials: "Daftar Materi",
      emptyMaterials: "Belum ada materi ajar untuk kelas ini.",
      createMaterialPrompt: "Buat materi baru di menu Materi Ajar dan pilih kelas ini.",
      taughtProgress: "Progress Pembelajaran",
      materialTaught: "Sudah Diajar",
      materialNotTaught: "Belum Diajar",
      durationTaught: "Durasi Diajar",
      btnStartTeaching: "Mulai Mengajar",
      btnStopTeaching: "Hentikan",
      toastAnotherTimerActive: "Silakan hentikan sesi mengajar yang aktif terlebih dahulu!",
      totalStudents: "Total: {{count}} siswa",
      newStudent: "Siswa Baru",
      addStudentTitle: "Tambah Siswa",
      addStudentDesc: "Masukkan nama dan Nomor Induk Siswa (NIS).",
      nameLabel: "Nama Lengkap",
      nisLabel: "NIS / Nomer Absen (opsional)",
      pasteBulk: "Paste Daftar (Bulk)",
      bulkTitle: "Masukan Daftar Siswa",
      bulkDesc: "Paste daftar nama dari Excel. 1 baris = 1 siswa. Format: Nama, NIS atau hanya Nama",
      bulkPlaceholder: "Budi Santoso, 1001\nCitra Lestari, 1002\nAgus",
      btnProcess: "Proses",
      thNo: "No",
      thNis: "NIS",
      thName: "Nama Siswa",
      thAction: "Aksi",
      emptyStudents: "Belum ada siswa di kelas ini.",
      tooltipProfile: "Lihat Detail Profil Siswa",
      tooltipRemove: "Keluarkan Siswa dari Kelas",
      confirmRemove: "Hapus {{name}}?",
      removedAlert: "Dihapus",
      totalHours: "Total Jam Mengajar",
      overallIn: "Keseluruhan di {{className}}",
      bySubject: "Berdasarkan Mata Pelajaran",
      emptyLogText: "Belum ada rekaman jam mengajar.",
      teachingHistory: "Histori Mengajar",
      useTrackerHint: "Gunakan fitur Time Tracker di menu atas untuk mulai mencatat",
      noSubject: "Tanpa Mapel (Umum)",
      deletedSubject: "Mapel Dihapus",
      minutes: "Menit",
      errorEmptyName: "Nama siswa tidak boleh kosong",
      successAdd: "Siswa ditambahkan",
      successBulk: "{{count}} siswa berhasil ditambahkan"
    },
    attendancePage: {
      title: "Presensi",
      desc: "Catat kehadiran siswa secara offline.",
      recapDesc: "Lihat dan pantau rekapitulasi data kehadiran siswa secara keseluruhan.",
      tabAttendance: "Presensi",
      tabRecap: "Rekap",
      selectClass: "Pilih Kelas",
      classPlaceholder: "Pilih Kelas...",
      noClass: "Tidak ada kelas",
      subjectLabel: "Mata Pelajaran",
      subjectPlaceholder: "Semua Mata Pelajaran",
      generalSubject: "-- Umum (Tidak Terikat Mapel) --",
      dateLabel: "Pilih Tanggal",
      datePlaceholder: "Pilih tanggal",
      emptyStudents: "Belum ada siswa di kelas ini.",
      chartTitle: "Distribusi Kehadiran",
      chartCountLabel: "Jumlah",
      totalStudents: "Total Siswa",
      scheduled: "Terjadwal",
      setAll: "Set Semua:",
      setAllPresent: "Semua Hadir",
      thNo: "No",
      thName: "Nama Siswa",
      thStatus: "Status Presensi",
      btnSave: "Simpan Presensi",
      btnSaving: "Menyimpan...",
      successSave: "Data presensi berhasil disimpan",
      errorSave: "Gagal menyimpan presensi",
      recapTitle: "Rekap Presensi",
      totalTeaching: "Total Mengajar",
      days: "Hari",
      recapTotal: "Rekap Total",
      emptyRecap: "Belum ada catatan presensi untuk filter terpilih.",
      statusPresent: "Hadir",
      statusSick: "Sakit",
      statusExcused: "Izin",
      statusAbsent: "Alpa"
    },
    gradebookPage: {
      title: "Daftar Nilai",
      desc: "Input nilai evaluasi (Tugas/Ulangan) berdasarkan Mata Pelajaran.",
      selectClass: "Pilih Kelas...",
      allSubjects: "Semua Mata Pelajaran",
      generalSubject: "-- Umum (Tidak Terikat Mapel) --",
      emptyState: "Pilih Kelas untuk melihat daftar nilai.",
      tableTitle: "Tabel Nilai",
      btnNewCol: "Tambah Kolom Evaluasi",
      modalTitle: "Evaluasi Baru",
      modalDesc: "Contoh: Tugas 1, Ulangan Harian, UTS",
      evalName: "Nama Evaluasi",
      btnCancel: "Batal",
      btnAdd: "Tambah",
      emptyStudents: "Belum ada siswa di kelas ini.",
      thNo: "No",
      thName: "Nama Siswa",
      thStatus: "Status",
      thAction: "Aksi",
      average: "Rata-rata",
      rename: "Ubah Nama",
      deleteColumn: "Hapus Kolom",
      renameTitle: "Ubah Nama Kolom",
      renameDesc: "Masukkan nama baru untuk kolom evaluasi ini.",
      renameSuccess: "Nama kolom berhasil diubah",
      renameError: "Nama kolom tidak dapat diubah. Pastikan nama valid dan tidak bentrok dengan evaluasi lain.",
      deleteSuccess: "Kolom berhasil dihapus",
      confirmDeleteColumn: "Hapus kolom \"{{name}}\" beserta seluruh nilainya?"
    },
    notesPage: {
      title: "Materi & Catatan",
      desc: "Pusat materi ajar dan catatan pribadi guru (mendukung Markdown).",
      btnNew: "Tulis Catatan",
      modalNewTitle: "Catatan Baru",
      modalEditTitle: "Edit Catatan",
      labelTitle: "Judul",
      placeholderTitle: "Misal: Bab 1 - Bilangan Bulat",
      labelClass: "Terkait Kelas (Opsional)",
      placeholderClass: "Pilih Kelas...",
      allClasses: "Semua Kelas / Umum",
      labelSubject: "Terkait Mata Pelajaran (Opsional)",
      placeholderSubject: "Pilih Mata Pelajaran...",
      noSubject: "Tidak Terikat Mapel",
      btnWrite: "Tulis",
      btnPreview: "Pratinjau",
      placeholderContent: "Gunakan Markdown untuk memformat teks (misal: **Tebal**, *Miring*, - List, # Heading)...",
      previewEmpty: "Pratinjau kosong...",
      btnCancel: "Batal",
      btnSave: "Simpan Catatan",
      btnDelete: "Hapus",
      btnClose: "Tutup",
      btnEdit: "Edit",
      confirmDelete: "Hapus catatan ini secara permanen?",
      successDelete: "Dihapus",
      successSave: "Catatan disimpan",
      successUpdate: "Catatan diperbarui",
      errorSave: "Gagal menyimpan",
      errorEmptyTitle: "Judul wajib diisi",
      tabMaterial: "Materi Ajar",
      tabJournal: "Jurnal Guru",
      tabEvaluation: "Soal Evaluasi",
      emptyStateTitle: "Belum ada catatan",
      emptyStateDesc: "Buat catatan dengan dukungan Markdown untuk modul Anda.",
      btnReadFull: "Baca Full",
      tooltipEdit: "Edit Catatan",
      tooltipDelete: "Hapus Catatan"
    },
    materialsPage: {
      title: "Materi Ajar",
      desc: "Pusat materi dan modul ajar guru (mendukung Markdown).",
      btnNew: "Tulis Materi",
      modalNewTitle: "Materi Baru",
      modalEditTitle: "Edit Materi",
      placeholderTitle: "Misal: Bab 1 - Bilangan Bulat",
      placeholderContent: "Tulis materi ajar Anda di sini menggunakan Markdown...",
      emptyStateTitle: "Belum ada materi ajar",
      emptyStateDesc: "Mulai buat materi atau bahan ajar Anda dengan dukungan Markdown.",
      presentBtn: "Presentasikan",
      insertQuiz: "Sisipkan Kuis",
      backShortcut: "Kembali (Esc)",
      saveShortcut: "Simpan (Ctrl+S)",
      saving: "Menyimpan...",
      shortcutsHint: "Ctrl+S simpan - Esc kembali",
      words: "kata",
      quizTemplateQuestion: "Soal {{n}}",
      quizTemplatePrompt: "Tulis pertanyaan di sini.",
      quizTemplateCorrect: "Pilihan jawaban benar",
      quizTemplateOther: "Pilihan jawaban lain"
    },
    presentationView: {
      prev: "Sebelumnya",
      next: "Berikutnya",
      finish: "Selesai",
      exitBtn: "Keluar",
      slide: "Slide",
      navigate: "navigasi",
      exit: "keluar",
      coverSlide: "Sampul",
      noSlides: "Tidak ada slide untuk ditampilkan.",
      noSlidesHint: "Gunakan heading ## untuk membagi materi menjadi slide.",
      backBtn: "Kembali",
      clickToStart: "Tekan → atau klik untuk memulai",
      quizProgress: "Benar",
      quizScore: "Skor kuis:",
      answerToContinue: "Pilih jawaban untuk melanjutkan"
    },
    journalsPage: {
      title: "Jurnal Guru",
      desc: "Log mengajar harian guru.",
      btnNew: "Tulis Catatan",
      modalNewTitle: "Catatan Baru",
      modalEditTitle: "Edit Catatan",
      placeholderTitle: "Misal: Jurnal Kelas XII - Pertemuan 1",
      placeholderContent: "Tulis catatan jurnal di sini...",
      emptyStateTitle: "Belum ada catatan",
      emptyStateDesc: "Buat jurnal guru baru."
    },
    evaluationsPage: {
      title: "Soal Evaluasi",
      desc: "Kumpulan soal evaluasi siswa.",
      btnNew: "Buat Soal",
      modalNewTitle: "Soal Baru",
      modalEditTitle: "Edit Soal",
      placeholderTitle: "Misal: Soal UTS Matematika",
      placeholderContent: "Tulis butir soal evaluasi di sini...",
      emptyStateTitle: "Belum ada soal",
      emptyStateDesc: "Buat soal evaluasi baru.",
      quizFormatTitle: "Format kuis interaktif:",
      quizFormatUse: "Gunakan",
      quizFormatQuestionExample: "## Soal N",
      quizFormatOptionExample: "* Opsi",
      quizFormatQuestion: "untuk judul soal,",
      quizFormatOption: "untuk pilihan, dan",
      quizFormatCorrect: "untuk menandai jawaban benar."
    },
    calendarPage: {
      title: "Kalender & Tugas",
      desc: "Kelola jadwal evaluasi, agenda mengajar, dan tenggat waktu.",
      btnAdd: "Tambah Tugas",
      selectDateText: "Pilih Tanggal",
      listDesc: "Daftar tugas pada tanggal ini",
      emptyState: "Tidak ada agenda untuk hari ini",
      tooltipMarkUndone: "Tandai Belum Selesai",
      tooltipMarkDone: "Tandai Selesai",
      tooltipDelete: "Hapus Tugas",
      modalNewTitle: "Tambah Tugas / Agenda Baru",
      modalEditTitle: "Edit Tugas / Agenda",
      modalDesc: "Detailkan agenda atau jadwal kelas Anda di sini.",
      labelTitle: "Judul Tugas / Agenda *",
      placeholderTitle: "Rapat Orang Tua, Ulangan Harian...",
      labelDate: "Tanggal *",
      selectBtn: "Pilih",
      labelClass: "Kelas (Opsional)",
      placeholderClass: "Pilih Kelas",
      noClass: "-- Umum (Tidak Terikat) --",
      labelSubject: "Mata Pelajaran (Opsional)",
      placeholderSubject: "Pilih Mata Pelajaran",
      noSubject: "-- Tidak Terikat --",
      labelStartTime: "Waktu Mulai",
      labelEndTime: "Waktu Selesai",
      labelDeadlineDate: "Tanggal Deadline",
      labelDeadlineTime: "Waktu Deadline",
      btnRemove: "Hapus",
      labelDesc: "Deskripsi",
      placeholderDesc: "Catatan tambahan untuk tugas ini...",
      labelTags: "Tags / Label",
      placeholderTags: "Ketik lalu enter...",
      tagHelper: "Tekan Enter atau Koma untuk menambahkan tag",
      btnCancel: "Batal",
      btnSave: "Simpan",
      errorEmptyTitle: "Judul tugas wajib diisi",
      errorEmptyDate: "Tanggal tugas wajib diisi",
      errorSave: "Gagal menyimpan tugas",
      successSaveNew: "Tugas baru berhasil ditambahkan",
      successSaveEdit: "Tugas berhasil diperbarui",
      deadlinePrefix: "Deadline:"
    },
    studentsPage: {
      title: "Data Master Siswa",
      desc: "Daftar seluruh siswa dari semua kelas yang Anda ampu.",
      searchPlaceholder: "Cari nama siswa atau NIS...",
      filterAllClasses: "Semua Kelas",
      thNameAndNis: "NAMA & NIS",
      thClass: "KELAS",
      thAction: "AKSI",
      emptyFiltered: "Tidak ada siswa yang cocok dengan pencarian.",
      emptyTitle: "Belum ada data siswa",
      emptyDesc: "Tambahkan siswa melalui menu Kelas Saya untuk mulai mengelola data mereka.",
      goToClasses: "Ke Menu Kelas Saya",
      tooltipProfile: "Lihat Profil Siswa",
      tooltipDelete: "Hapus Data Siswa",
      confirmDelete: "Hapus {{name}} secara permanen beserta seluruh presensi, nilai, catatan, dan keanggotaan mata pelajarannya?",
      successDelete: "Siswa berhasil dihapus",
      btnImport: "Import Excel",
      btnAdd: "Tambah Siswa",
      importTitle: "Import Data Siswa",
      importStep1: "1. Pilih Kelas Target",
      importStep2: "2. Gunakan Template (Opsional)",
      importStep3: "3. Upload File Excel (.xlsx)",
      btnDownloadTemplate: "Download Template",
      templateDesc: "Pastikan file Excel Anda memiliki kolom Nama dan NIS.",
      duplicatePolicyLabel: "Kebijakan NIS Duplikat",
      duplicatePolicyReject: "Batalkan seluruh import",
      duplicatePolicySkip: "Lewati baris duplikat",
      duplicatePolicyDesc: "NIS dibandingkan dengan data yang sudah ada dan antarbaris dalam file.",
      selectClassTarget: "Pilih kelas terlebih dahulu untuk membuka upload.",
      classPlaceholder: "Pilih kelas...",
      addTitle: "Tambah Siswa Baru",
      classLabel: "Kelas",
      nameLabel: "Nama Lengkap",
      namePlaceholder: "Masukkan nama siswa",
      nisLabel: "NIS / No. Induk",
      nisPlaceholder: "Masukkan NIS (opsional)",
      btnSave: "Simpan Siswa",
      errorEmptyClass: "Nama siswa dan kelas wajib diisi",
      successAdd: "Siswa berhasil ditambahkan",
      successEdit: "Data {{name}} berhasil diubah",
      editTitle: "Edit Data Siswa",
      errorSelectClass: "Silakan pilih kelas terlebih dahulu sebelum mengimpor.",
      errorEmptyExcel: "File Excel kosong atau format tidak sesuai.",
      successImport: "{{count}} siswa berhasil diimpor!",
      skippedDuplicates: "{{count}} baris dengan NIS duplikat dilewati.",
      errorNoValidData: "Tidak ada data valid yang dapat diimpor.",
      errorProcessExcel: "Terjadi kesalahan saat memproses file Excel.",
      thName: "Nama Siswa",
      thNis: "NIS",
      noStudentsFound: "Tidak ada siswa yang ditemukan.",
      deletedClass: "Kelas Terhapus"
      ,importLinked: "siswa lama ditautkan ke kelas ini",
      importPreviewTitle: "Pratinjau impor",
      importPreviewRows: "baris siap diproses",
      importPreviewLinked: "siswa dengan NIS yang sudah ada akan ditautkan",
      importConfirm: "Konfirmasi Impor"
    },
    studentDetail: {
      notFound: "Data siswa tidak ditemukan.",
      studentProfile: "Profil Siswa",
      profileDesc: "Detail statistik dan historis absensi.",
      btnEdit: "Edit Data",
      btnSave: "Simpan Data",
      nameLabel: "Nama Siswa",
      nisLabel: "NIS",
      genderLabel: "Jenis Kelamin",
      genderMale: "Laki-laki",
      genderFemale: "Perempuan",
      genderUnset: "Belum diatur",
      phoneLabel: "No. HP Ortu/Wali",
      phonePlaceholder: "Contoh: 0812...",
      noteLabel: "Catatan Penting",
      notePlaceholder: "Contoh: Anak memiliki riwayat asma...",
      tabStats: "Statistik",
      tabAttendance: "Log Presensi",
      tabGrades: "Riwayat Nilai",
      statsAttendance: "Bentuk Kehadiran",
      statsGrades: "Rata-rata Nilai",
      gradeBook: "Buku Nilai",
      logStatus: "Status",
      logNote: "Keterangan",
      logEmpty: "Belum ada catatan presensi.",
      gradeTitle: "Judul",
      gradeScore: "Nilai",
      gradeEmpty: "Belum ada nilai yang tercatat.",
      successUpdate: "Data siswa berhasil diupdate",
      attendanceFormat: "Format"
    },
    quizView: {
      question: "Soal",
      of: "dari",
      score: "Skor",
      points: "poin",
      correct: "Benar",
      wrong: "Salah",
      prev: "Sebelumnya",
      next: "Berikutnya",
      finish: "Lihat Hasil",
      finishTitle: "Kuis Selesai! 🎉",
      finalScore: "Skor Akhir",
      totalCorrect: "Jawaban Benar",
      totalWrong: "Jawaban Salah",
      totalQuestions: "Total Soal",
      reviewBtn: "Review Jawaban",
      backBtn: "Kembali ke Daftar",
      badgeInteractive: "Kuis Interaktif",
      badgeNQuestions: "{{n}} Soal",
      noQuestions: "Soal ini tidak mengandung format kuis interaktif.",
      noQuestionsHint: "Tambahkan opsi jawaban dengan format: * Pilihan A [*] untuk menandai jawaban benar.",
      templateBtn: "Sisipkan Contoh Soal",
      startQuiz: "Mulai Kuis",
      answeredCorrectly: "Benar! +{{pts}} poin",
      answeredWrong: "Salah. Jawaban benar adalah:",
      exitQuiz: "Keluar Kuis",
      questionProgress: "Soal {{current}} dari {{total}}"
    },
    shortcuts: {
      desc_D: 'Ke Halaman Dashboard',
      desc_P: 'Ke Halaman Profile',
      desc_M: 'Ke Halaman Mata Pelajaran (Subjects)',
      desc_C: 'Ke Halaman Kelas (Classes)',
      desc_S: 'Ke Halaman Siswa (Students)',
      desc_A: 'Ke Halaman Kehadiran (Attendance)',
      desc_G: 'Ke Halaman Buku Nilai (Gradebook)',
      desc_N: 'Ke Halaman Materi Ajar',
      desc_J: 'Ke Halaman Jurnal Guru',
      desc_E: 'Ke Halaman Soal Evaluasi',
      desc_T: 'Ke Halaman Kalender (Tasks)',
      desc_B: 'Ke Halaman Pengaturan & Backup',
      desc_H: 'Ke Halaman Bantuan (Help/About)'
    },
    about: {
      title: "Tentang EduPlanner",
      desc: "EduPlanner adalah sistem informasi manajemen sekolah ringan yang berjalan sepenuhnya di browser Anda. Dirancang untuk membantu guru mengelola kelas, siswa, absensi, dan nilai secara offline tanpa perlu terhubung ke server eksternal.",
      keyboardAccess: "Aksesibilitas Keyboard",
      keyboardDesc: "EduPlanner dirancang untuk dapat dioperasikan dengan cepat menggunakan keyboard. Berikut adalah daftar tombol pintas yang dapat Anda gunakan:",
      releaseStatus: "Beta Publik",
      releaseStatusDesc: "Versi prarilis untuk evaluasi dan penggunaan terbatas dengan backup mandiri. Belum memiliki jaminan stabilitas.",
      version: "Versi",
      revision: "Revisi",
      devInfo: "Informasi Pengembang",
      devDesc: "Aplikasi ini dikembangkan oleh",
      key: "Tombol",
      action: "Aksi"
    },
    settings: {
      title: "Pengaturan & Backup",
      desc: "Kelola data offline dan tampilan aplikasi Anda.",
      groupAppearance: "Tampilan",
      groupBackup: "Backup / Restore",
      prefLang: "Preferensi Bahasa",
      prefTheme: "Tema Tampilan",
      themeLight: "Terang (Light)",
      themeDark: "Gelap (Dark)",
      themeSystem: "Sistem (Default)",
      notificationPrivacyLabel: "Privasi Notifikasi",
      notificationPrivacyDescription: "Secara default, notifikasi menyembunyikan nama kelas, mata pelajaran, dan jam agar tidak terlihat di lock screen. Aktifkan hanya pada perangkat pribadi yang terlindungi.",
      notificationDetailsHidden: "Detail Disembunyikan",
      notificationDetailsShown: "Detail Ditampilkan",
      syncTitle: "Provider Backup Eksperimental",
      providerLabel: "Provider Backup",
      providerDisconnected: "Tidak Terhubung",
      providerMock: "Mock Lokal (Khusus Pengembangan)",
      disconnectedStatusTitle: "Provider tidak terhubung",
      disconnectedStatusDesc: "Tidak ada backup cloud yang aktif. Gunakan Download Backup untuk menyimpan salinan di luar perangkat ini.",
      mockStatusTitle: "Simulasi lokal — bukan backup cloud",
      mockStatusDesc: "Mode mock hanya menyimpan salinan di localStorage browser ini. Data tidak dikirim ke Google Drive atau layanan cloud lain dan dapat hilang bersama data browser.",
      mockAutoBackup: "Auto-backup mock lokal (5 menit)",
      statusActive: "Aktif",
      statusDisabled: "Nonaktif",
      mockBackupNow: "Buat Mock Backup",
      mockBackingUp: "Membuat...",
      mockRestore: "Restore Mock",
      mockRestoring: "Memulihkan...",
      mockBackupSuccess: "Mock backup lokal berhasil dibuat. Data tidak diunggah ke cloud.",
      mockBackupError: "Gagal membuat mock backup lokal",
      mockRestoreEmpty: "Belum ada mock backup lokal yang dapat dipulihkan.",
      mockRestoreConfirm: "PERINGATAN: Restore mock akan menimpa seluruh data saat ini. Anda yakin ingin melanjutkan?",
      mockRestoreSuccess: "Data berhasil dipulihkan dari mock backup lokal.",
      mockRestoreError: "Gagal memulihkan mock backup lokal",
      importantTitle: "Penting",
      importantDesc: "EduPlanner menyimpan data **sepenuhnya di dalam browser ini** (IndexedDB). Jika Anda menghapus \"History/Cache\" browser Anda, data ini bisa hilang. Sangat disarankan untuk rutin melakukan backup.",
      exportTitle: "Export Data (Backup)",
      exportDesc: "Unduh seluruh data Anda ke file .json",
      exportText: "Simpan file ini di flashdisk, Google Drive, atau kirim ke email Anda sendiri sebagai cadangan.",
      importTitle: "Import Data (Restore)",
      importDesc: "Kembalikan data dari file backup .json",
      importText: "Data saat ini akan DIHAPUS dan digantikan sepenuhnya oleh data dari file backup.",
      btnExport: "Download Backup",
      btnImporting: "Mengimpor...",
      btnImport: "Pilih File Backup",
      successExport: "Backup berhasil diunduh",
      errorExport: "Gagal melakukan backup",
      confirmImport: "PERINGATAN: Mengimpor data akan menimpa seluruh data yang ada saat ini. Anda yakin ingin melanjutkan?",
      recoveryDownloaded: "Snapshot pemulihan data saat ini telah diunduh.",
      recoveryConfirm: "Pastikan file recovery eduplanner_pre_restore sudah tersimpan dengan aman. Lanjutkan restore dan ganti seluruh data saat ini?",
      recoveryCancelled: "Restore dibatalkan. Database saat ini tidak diubah.",
      previewTitle: "Tinjau Restore Backup",
      previewDescription: "Periksa isi dan status backup sebelum mengganti database lokal.",
      previewSource: "Sumber",
      previewSourceCurrent: "Format saat ini",
      previewSourceLegacy: "Format legacy",
      previewVersion: "Migrasi versi",
      previewDatabaseVersion: "Versi database",
      previewTotalRecords: "Total record",
      previewExportedAt: "Tanggal ekspor",
      previewUnavailable: "Tidak tersedia",
      previewIntegrity: "Integritas",
      previewIntegrityValid: "Valid",
      previewTableCounts: "Jumlah record per tabel",
      previewMigrationWarnings: "Peringatan migrasi legacy",
      previewLegacyWarning: "Tabel {{table}} tidak tersedia pada backup lama dan akan dibuat kosong.",
      previewRecoveryCreated: "Snapshot recovery telah diunduh",
      previewConfirmReplace: "Saya memahami seluruh data lokal saat ini akan diganti setelah snapshot recovery dibuat.",
      previewConfirmRecoverySaved: "Saya memastikan file recovery sudah tersimpan dengan aman dan menyetujui penggantian seluruh data lokal.",
      previewCancel: "Batal",
      previewDownloadRecovery: "Unduh Recovery & Lanjutkan",
      previewPreparingRecovery: "Menyiapkan recovery...",
      previewRestoreNow: "Restore Sekarang",
      previewTableProfile: "Profil",
      previewTableSubjects: "Mata pelajaran",
      previewTableClasses: "Kelas",
      previewTableStudents: "Siswa",
      previewTableAttendances: "Absensi",
      previewTableGrades: "Nilai",
      previewTableNotes: "Catatan & materi",
      previewTableTasks: "Tugas",
      previewTableTeachingSessions: "Sesi mengajar",
      previewTableStudentNotes: "Catatan siswa",
      previewTableSchedules: "Jadwal",
      previewTableAcademicPeriods: "Periode Akademik",
      previewTableClassEnrollments: "Keanggotaan Kelas",
      successImport: "Data berhasil diimpor!",
      errorImport: "Format file tidak valid atau terjadi kesalahan"
    },
    timeTracker: {
      btnStart: "Mulai Mengajar",
      btnStop: "Stop",
      tooltipStop: "Hentikan dan Simpan Waktu Mengajar",
      title: "Pencatat Waktu",
      desc: "Catat waktu mengajar Anda di kelas ini.",
      selectClass: "Pilih Kelas *",
      selectClassPlaceholder: "Pilih Kelas...",
      selectSubject: "Mata Pelajaran (Opsional)",
      selectSubjectPlaceholder: "Semua / Umum",
      general: "-- Umum --",
      startTimer: "Mulai Waktu",
      errorNoClass: "Silakan pilih kelas terlebih dahulu!",
      successStart: "Waktu dimulai",
      successSave: "Waktu mengajar dicatat: {{minutes}} menit",
      errorSave: "Gagal mencatat waktu mengajar"
    },
    common: {
      save: "Simpan",
      cancel: "Batal",
      delete: "Hapus",
      edit: "Edit",
      add: "Tambah",
      close: "Tutup",
      success: "Berhasil",
      error: "Gagal",
      loading: "Memuat data...",
      empty: "Belum ada data",
      search: "Cari...",
      total: "Total",
      name: "Nama",
      description: "Deskripsi",
      date: "Tanggal",
      hour: "Jam",
      minute: "Menit",
      clear: "Hapus"
    },
    securityImages: {
      externalTitle: "Gambar eksternal diblokir",
      externalDescription: "Memuat gambar ini akan menghubungi situs pihak ketiga dan mengungkapkan alamat IP perangkat Anda.",
      loadExternal: "Muat gambar eksternal",
      blockedTitle: "Sumber gambar tidak aman dan tidak dapat dimuat"
    },
    scheduling: {
      tabSchedules: "Jadwal",
      addSchedule: "Tambah Jadwal",
      addDialogTitle: "Tambah Jadwal Mengajar",
      addDialogDesc: "Atur jadwal mengajar berulang untuk kelas ini.",
      editDialogTitle: "Edit Jadwal Mengajar",
      editDialogDesc: "Perbarui pengaturan jadwal mengajar berulang.",
      subjectLabel: "Mata Pelajaran",
      recurrenceLabel: "Perulangan",
      recurrenceDaily: "Harian",
      recurrenceWeekly: "Mingguan",
      recurrenceMonthly: "Bulanan",
      daysOfWeekLabel: "Hari",
      startDateLabel: "Tanggal Mulai",
      endCriteriaLabel: "Batas Berakhir",
      endCriteriaCount: "Jumlah Perulangan (Frekuensi)",
      endCriteriaDate: "Tanggal Berakhir",
      endCriteriaNone: "Selamanya / Tidak Terbatas",
      countLabel: "Ulangi Sebanyak (Kali)",
      endDateLabel: "Tanggal Selesai",
      timeRangeLabel: "Waktu Mengajar",
      startTimeLabel: "Jam Mulai",
      endTimeLabel: "Jam Selesai",
      reminderLabel: "Pengingat Notifikasi",
      reminderOff: "Nonaktif",
      reminder5Min: "5 Menit Sebelum",
      reminder15Min: "15 Menit Sebelum",
      reminder30Min: "30 Menit Sebelum",
      reminder1Hour: "1 Jam Sebelum",
      noSchedules: "Belum ada jadwal mengajar untuk kelas ini.",
      createSchedulePrompt: "Mulai tambahkan jadwal mengajar berulang agar kelas terdeteksi otomatis di Kalender dan menerima notifikasi push.",
      successAdd: "Jadwal berhasil ditambahkan",
      errorIncomplete: "Silakan isi jam mulai, jam selesai, dan tanggal mulai!",
      errorSave: "Gagal menyimpan jadwal!",
      successDelete: "Jadwal berhasil dihapus",
      confirmDelete: "Hapus jadwal mengajar berulang ini?",
      notificationBanner: "Aktifkan notifikasi browser untuk menerima pengingat jadwal mengajar kelas secara real-time.",
      btnEnableNotification: "Aktifkan Pengingat",
      notificationTitlePrivate: "Pengingat EduPlanner",
      notificationTitle: "🔔 Kelas Segera Dimulai!",
      notificationBodyPrivate: "Pengingat jadwal mengajar tersedia. Buka EduPlanner untuk melihat detail.",
      notificationBody: "Kelas {{className}} ({{subjectName}}) akan dimulai pada pukul {{startTime}}. Klik untuk membuka materi!",
      notificationBodyNoSubject: "Kelas {{className}} akan dimulai pada pukul {{startTime}}. Klik untuk membuka materi!"
    }
  },
  en: {
    sidebar: {
      dashboard: "Dashboard",
      profile: "Profile",
      subjects: "Subjects",
      classes: "Classes",
      students: "Students",
      attendance: "Attendance",
      gradebook: "Gradebook",
      notes: "Notes",
      materials: "Teaching Materials",
      journals: "Teacher Journals",
      evaluations: "Evaluations",
      calendar: "Calendar",
      settings: "Settings (Backup)",
      about: "About / Help",
      offlineMode: "Offline Mode Active",
      offlineDesc: "App is running offline in your browser",
      shortcut: "Shortcut",
      expandNav: "Expand Navigation",
      collapseNav: "Collapse Navigation",
      openNav: "Open Navigation"
    },
    topbar: {
      dashboard: "Dashboard Overview"
    },
    pwaUpdate: {
      title: "An EduPlanner update is available",
      description: "Save your work first. The update is applied and the page reloads only after you choose Update now.",
      later: "Later",
      updateNow: "Update now",
      updating: "Updating...",
      error: "The update could not be applied. Check your connection and try again."
    },
    dashboard: {
      exportBtn: "Export Data",
      exporting: "Exporting...",
      studentData: "TOTAL STUDENT DATA",
      registered: "ENROLLED",
      noStudentData: "No student data yet",
      studentScattered: "Students spread across {{totalClasses}} Classes",
      manageStudents: "Manage Students",
      quickAccess: "QUICK ENTRY ACCESS",
      main: "MAIN",
      others: "OTHERS",
      fillAttendance: "Fill Class Attendance",
      inputGrades: "Input Daily Grades",
      viewSchedule: "Teaching Schedule",
      activeClasses: "ACTIVE CLASSES",      totalClassesPrompt: "Total classes that",
      yourTeach: "you teach",
      recentNotes: "RECENT NOTES",
      seeAllDesc: "See all notes \u2192",
      noNotes: "No notes yet.",
      tasksPending: "Tasks Pending",
      localStorageStr: "Local Storage",
      browserIndexedDbStr: "Browser IndexedDB",
      upcomingClassesToday: "Today's Schedule",
      noUpcomingClasses: "No classes scheduled for today. Have a great rest! 🌟",
      teachingHoursTitle: "Teaching Hours Analysis",
      teachingHoursDesc: "Your logged teaching sessions duration",
      sixMonths: "6 Months",
      twelveMonths: "12 Months",
      hours: "Hours",
      minutes: "Minutes",
      ongoing: "Ongoing",
      upcoming: "Upcoming",
      finished: "Finished",
      openClass: "Open Class",
      totalHours: "Total Hours",
      totalSessions: "Total Sessions",
      sessionsUnit: "Sessions"
    },
    profilePage: {
      title: "Teacher Profile",
      desc: "Manage teacher identity that will appear on reports.",
      detailTitle: "Profile Details",
      detailDesc: "This information is added to report cards or report slips.",
      fullName: "Full Name (with title)",
      fullNamePlaceholder: "Example: Budi Santoso, M.Pd.",
      school: "School Name",
      schoolPlaceholder: "Example: SMA Negeri 1 Jakarta",
      role: "Position / Role",
      rolePlaceholder: "Example: Homeroom Teacher / Subject Teacher",
      email: "Email",
      emailPlaceholder: "example: name@school.sch.id",
      avatar: "Avatar URL",
      avatarPlaceholder: "Profile image URL (optional)",
      saveSuccess: "Profile saved successfully",
      saveError: "Failed to save profile",
      errorEmptyName: "Full name is required"
    },
    subjectsPage: {
      title: "Subjects",
      desc: "Manage the list of subjects you teach.",
      addSubject: "Add Subject",
      addDialogTitle: "Add New Subject",
      addDialogDesc: "Enter the subject name and an optional description.",
      nameLabel: "Subject Name (e.g., General Math)",
      namePlaceholder: "Subject Name...",
      descLabel: "Description (optional)",
      descPlaceholder: "Description...",
      emptyTitle: "No subjects yet",
      emptyDesc: "Start by adding a subject so you can link it when entering grades or attendance.",
      addFirstBtn: "Add Your First Subject",
      noDesc: "No description",
      errorEmpty: "Subject name cannot be empty",
      successAdd: "Subject successfully created",
      errorAdd: "Failed to create subject",
      confirmDelete: "Delete this subject? Grades, attendance, tasks, notes, and recurring schedules will be kept without a subject label. Linked teaching history will be deleted.",
      successDelete: "Subject deleted",
      manageStudents: "Manage Students",
      studentsCount: "{{count}} students",
      assignClass: "Assign Class",
      selectClass: "Select Class",
      btnAssign: "Assign Class",
      enrolledStudents: "Enrolled Students",
      emptyEnrolled: "No students enrolled in this subject yet.",
      removeClass: "Remove",
      btnSaveEnrolled: "Close",
      successAssign: "All class students have been successfully enrolled",
      successRemoveStudent: "Student removed from subject",
      tooltipManageStudents: "Manage Enrolled Students"
    },
    classesPage: {
      title: "My Classes",
      desc: "Manage the classes and students you teach.",
      addClass: "Add Class",
      addDialogTitle: "Add New Class",
      addDialogDesc: "Enter the class name and an optional description.",
      nameLabel: "Class Name (e.g., Grade 12 Science)",
      namePlaceholder: "Class Name...",
      descLabel: "Description (optional)",
      descPlaceholder: "Academic Year 2024/2025",
      emptyTitle: "No classes yet",
      emptyDesc: "Start by adding your first class to manage attendance and grades.",
      addFirstBtn: "Add Your First Class",
      noDesc: "No description",
      viewStudents: "View Students",
      deleteTooltip: "Delete Class",
      errorEmpty: "Class name cannot be empty",
      successAdd: "Class successfully created",
      errorAdd: "Failed to create class",
      editClass: "Edit Class",
      editDialogDesc: "Update this class name or description.",
      successUpdate: "Class updated successfully",
      errorUpdate: "Failed to update class",
      confirmDelete: "Permanently delete this class and all students, attendance, grades, materials, tasks, schedules, and teaching history?",
      successDelete: "Class deleted"
    },
    classDetail: {
      notFound: "Class not found.",
      management: "Class management and teaching log",
      tabStudents: "Student List",
      tabLog: "Teaching Log",
      tabMaterials: "Materials List",
      emptyMaterials: "No teaching materials for this class yet.",
      createMaterialPrompt: "Create new materials in the Teaching Materials menu and link them to this class.",
      taughtProgress: "Learning Progress",
      materialTaught: "Taught",
      materialNotTaught: "Not Taught",
      durationTaught: "Duration Taught",
      btnStartTeaching: "Start Teaching",
      btnStopTeaching: "Stop",
      toastAnotherTimerActive: "Please stop the active teaching session first!",
      totalStudents: "Total: {{count}} students",
      newStudent: "New Student",
      addStudentTitle: "Add Student",
      addStudentDesc: "Enter student name and ID.",
      nameLabel: "Full Name",
      nisLabel: "Student ID / Roll No (optional)",
      pasteBulk: "Paste List (Bulk)",
      bulkTitle: "Input Student List",
      bulkDesc: "Paste a list of names from Excel. 1 line = 1 student. Format: Name, ID or just Name",
      bulkPlaceholder: "John Doe, 1001\nJane Smith, 1002\nAlice",
      btnProcess: "Process",
      thNo: "No",
      thNis: "ID",
      thName: "Student Name",
      thAction: "Action",
      emptyStudents: "No students in this class yet.",
      tooltipProfile: "View Student Profile Details",
      tooltipRemove: "Remove Student from Class",
      confirmRemove: "Remove {{name}}?",
      removedAlert: "Deleted",
      totalHours: "Total Teaching Hours",
      overallIn: "Overall in {{className}}",
      bySubject: "By Subject",
      emptyLogText: "No teaching hours logged yet.",
      teachingHistory: "Teaching History",
      useTrackerHint: "Use the Time Tracker feature in the top menu to start recording",
      noSubject: "No Subject (General)",
      deletedSubject: "Deleted Subject",
      minutes: "Minutes",
      errorEmptyName: "Student name cannot be empty",
      successAdd: "Student added",
      successBulk: "{{count}} students successfully added"
    },
    attendancePage: {
      title: "Attendance",
      desc: "Record student attendance offline.",
      recapDesc: "Review and monitor overall student attendance recaps.",
      tabAttendance: "Attendance",
      tabRecap: "Recap",
      selectClass: "Select Class",
      classPlaceholder: "Select Class...",
      noClass: "No classes available",
      subjectLabel: "Subject",
      subjectPlaceholder: "All Subjects",
      generalSubject: "-- General (No Subject) --",
      dateLabel: "Select Date",
      datePlaceholder: "Select date",
      emptyStudents: "No students in this class yet.",
      chartTitle: "Attendance Distribution",
      chartCountLabel: "Count",
      totalStudents: "Total Students",
      scheduled: "Scheduled",
      setAll: "Set All:",
      setAllPresent: "All Present",
      thNo: "No",
      thName: "Student Name",
      thStatus: "Attendance Status",
      btnSave: "Save Attendance",
      btnSaving: "Saving...",
      successSave: "Attendance data successfully saved",
      errorSave: "Failed to save attendance",
      recapTitle: "Attendance Recap",
      totalTeaching: "Total Teaching",
      days: "Days",
      recapTotal: "Total Recap",
      emptyRecap: "No attendance records match the selected filter.",
      statusPresent: "Present",
      statusSick: "Sick",
      statusExcused: "Excused",
      statusAbsent: "Absent"
    },
    gradebookPage: {
      title: "Gradebook",
      desc: "Input evaluation grades (Assignments/Exams) based on Subjects.",
      selectClass: "Select Class...",
      allSubjects: "All Subjects",
      generalSubject: "-- General (No Subject) --",
      emptyState: "Select a Class to view the gradebook.",
      tableTitle: "Grades Table",
      btnNewCol: "Add Evaluation Column",
      modalTitle: "New Evaluation",
      modalDesc: "Example: Assignment 1, Quiz, Midterm",
      evalName: "Evaluation Name",
      btnCancel: "Cancel",
      btnAdd: "Add",
      emptyStudents: "No students in this class yet.",
      thNo: "No",
      thName: "Student Name",
      thStatus: "Status",
      thAction: "Action",
      average: "Average",
      rename: "Rename",
      deleteColumn: "Delete Column",
      renameTitle: "Rename Column",
      renameDesc: "Enter a new name for this evaluation column.",
      renameSuccess: "Column name updated",
      renameError: "The column could not be renamed. Make sure the name is valid and does not conflict with another evaluation.",
      deleteSuccess: "Column deleted",
      confirmDeleteColumn: "Delete column \"{{name}}\" and all of its grades?"
    },
    notesPage: {
      title: "Materials & Notes",
      desc: "Central hub for teaching materials and personal teacher notes (Markdown supported).",
      btnNew: "Write Note",
      modalNewTitle: "New Note",
      modalEditTitle: "Edit Note",
      labelTitle: "Title",
      placeholderTitle: "e.g., Chapter 1 - Integers",
      labelClass: "Related Class (Optional)",
      placeholderClass: "Select Class...",
      allClasses: "All Classes / General",
      labelSubject: "Related Subject (Optional)",
      placeholderSubject: "Select Subject...",
      noSubject: "No Subject Area",
      btnWrite: "Write",
      btnPreview: "Preview",
      placeholderContent: "Use Markdown to format text (e.g., **Bold**, *Italic*, - List, # Heading)...",
      previewEmpty: "Preview empty...",
      btnCancel: "Cancel",
      btnSave: "Save Note",
      btnDelete: "Delete",
      btnClose: "Close",
      btnEdit: "Edit",
      confirmDelete: "Permanently delete this note?",
      successDelete: "Deleted",
      successSave: "Note saved",
      successUpdate: "Note updated",
      errorSave: "Failed to save",
      errorEmptyTitle: "Title is required",
      tabMaterial: "Teaching Material",
      tabJournal: "Teacher Journal",
      tabEvaluation: "Evaluation Questions",
      emptyStateTitle: "No notes yet",
      emptyStateDesc: "Create Markdown-supported notes for your modules.",
      btnReadFull: "Read Full",
      tooltipEdit: "Edit Note",
      tooltipDelete: "Delete Note"
    },
    materialsPage: {
      title: "Teaching Materials",
      desc: "Central hub for teaching materials and modules (Markdown supported).",
      btnNew: "Write Material",
      modalNewTitle: "New Material",
      modalEditTitle: "Edit Material",
      placeholderTitle: "e.g., Chapter 1 - Integers",
      placeholderContent: "Write your teaching material here using Markdown...",
      emptyStateTitle: "No teaching materials yet",
      emptyStateDesc: "Start creating your teaching materials or modules with Markdown support.",
      presentBtn: "Present",
      insertQuiz: "Insert Quiz",
      backShortcut: "Back (Esc)",
      saveShortcut: "Save (Ctrl+S)",
      saving: "Saving...",
      shortcutsHint: "Ctrl+S save - Esc back",
      words: "words",
      quizTemplateQuestion: "Question {{n}}",
      quizTemplatePrompt: "Write your question here.",
      quizTemplateCorrect: "Correct answer option",
      quizTemplateOther: "Other answer option"
    },
    presentationView: {
      prev: "Previous",
      next: "Next",
      finish: "Done",
      exitBtn: "Exit",
      slide: "Slide",
      navigate: "navigate",
      exit: "exit",
      coverSlide: "Cover",
      noSlides: "No slides to display.",
      noSlidesHint: "Use ## headings to split your content into slides.",
      backBtn: "Go Back",
      clickToStart: "Press → or click to start",
      quizProgress: "Correct",
      quizScore: "Quiz score:",
      answerToContinue: "Choose an answer to continue"
    },
    journalsPage: {
      title: "Teacher Journals",
      desc: "Daily teaching logs.",
      btnNew: "Write Note",
      modalNewTitle: "New Note",
      modalEditTitle: "Edit Note",
      placeholderTitle: "e.g., Class XII Journal - Session 1",
      placeholderContent: "Write journal notes here...",
      emptyStateTitle: "No notes yet",
      emptyStateDesc: "Create new teacher journals."
    },
    evaluationsPage: {
      title: "Evaluations",
      desc: "Collections of student evaluation questions.",
      btnNew: "Write Question",
      modalNewTitle: "New Question",
      modalEditTitle: "Edit Question",
      placeholderTitle: "e.g., Math Midterm",
      placeholderContent: "Write evaluation questions here...",
      emptyStateTitle: "No questions yet",
      emptyStateDesc: "Create new evaluation questions.",
      quizFormatTitle: "Interactive quiz format:",
      quizFormatUse: "Use",
      quizFormatQuestionExample: "## Question N",
      quizFormatOptionExample: "* Option",
      quizFormatQuestion: "for the question title,",
      quizFormatOption: "for an option, and",
      quizFormatCorrect: "to mark the correct answer."
    },
    calendarPage: {
      title: "Calendar & Tasks",
      desc: "Manage evaluation schedules, teaching agenda, and deadlines.",
      btnAdd: "Add Task",
      selectDateText: "Select Date",
      listDesc: "List of tasks for this date",
      emptyState: "No agenda for today",
      tooltipMarkUndone: "Mark as Undone",
      tooltipMarkDone: "Mark as Done",
      tooltipDelete: "Delete Task",
      modalNewTitle: "Add New Task / Agenda",
      modalEditTitle: "Edit Task / Agenda",
      modalDesc: "Detail your agenda or class schedule here.",
      labelTitle: "Task / Agenda Title *",
      placeholderTitle: "Parent Meeting, Daily Quiz...",
      labelDate: "Date *",
      selectBtn: "Select",
      labelClass: "Class (Optional)",
      placeholderClass: "Select Class",
      noClass: "-- General (Unbound) --",
      labelSubject: "Subject (Optional)",
      placeholderSubject: "Select Subject",
      noSubject: "-- Unbound --",
      labelStartTime: "Start Time",
      labelEndTime: "End Time",
      labelDeadlineDate: "Deadline Date",
      labelDeadlineTime: "Deadline Time",
      btnRemove: "Remove",
      labelDesc: "Description",
      placeholderDesc: "Additional notes for this task...",
      labelTags: "Tags / Labels",
      placeholderTags: "Type and enter...",
      tagHelper: "Press Enter or Comma to add tag",
      btnCancel: "Cancel",
      btnSave: "Save",
      errorEmptyTitle: "Task title is required",
      errorEmptyDate: "Task date is required",
      errorSave: "Failed to save task",
      successSaveNew: "New task successfully added",
      successSaveEdit: "Task successfully updated",
      deadlinePrefix: "Deadline:"
    },
    studentsPage: {
      title: "Students Master Data",
      desc: "List of all students across all your classes.",
      searchPlaceholder: "Search student name or ID...",
      filterAllClasses: "All Classes",
      thNameAndNis: "NAME & ID",
      thClass: "CLASS",
      thAction: "ACTION",
      emptyFiltered: "No students match your search.",
      emptyTitle: "No student data yet",
      emptyDesc: "Add students through the My Classes menu to start managing their data.",
      goToClasses: "Go to Classes Menu",
      tooltipProfile: "View Student Profile",
      tooltipDelete: "Delete Student Data",
      confirmDelete: "Permanently delete {{name}} and all attendance, grades, notes, and subject enrollment records?",
      successDelete: "Student deleted",
      btnImport: "Import Excel",
      btnAdd: "Add Student",
      importTitle: "Import Student Data",
      importStep1: "1. Select Target Class",
      importStep2: "2. Use Template (Optional)",
      importStep3: "3. Upload Excel File (.xlsx)",
      btnDownloadTemplate: "Download Template",
      templateDesc: "Ensure your Excel file has Name and ID columns.",
      duplicatePolicyLabel: "Duplicate ID Policy",
      duplicatePolicyReject: "Cancel the entire import",
      duplicatePolicySkip: "Skip duplicate rows",
      duplicatePolicyDesc: "IDs are checked against existing data and other rows in the file.",
      selectClassTarget: "Select class target before uploading.",
      classPlaceholder: "Select class...",
      addTitle: "Add New Student",
      classLabel: "Class",
      nameLabel: "Full Name",
      namePlaceholder: "Enter student name",
      nisLabel: "Student ID / Roll No",
      nisPlaceholder: "Enter ID (optional)",
      btnSave: "Save Student",
      errorEmptyClass: "Student name and class are required",
      successAdd: "Student successfully added",
      successEdit: "{{name}} details updated",
      editTitle: "Edit Student Data",
      errorSelectClass: "Please select a class before importing.",
      errorEmptyExcel: "Excel file is empty or format is invalid.",
      successImport: "{{count}} students successfully imported!",
      skippedDuplicates: "{{count}} rows with duplicate IDs were skipped.",
      errorNoValidData: "No valid data could be imported.",
      errorProcessExcel: "Error processing the Excel file.",
      thName: "Student Name",
      thNis: "ID",
      noStudentsFound: "No students found.",
      deletedClass: "Deleted Class"
      ,importLinked: "existing students linked to this class",
      importPreviewTitle: "Import preview",
      importPreviewRows: "rows ready to process",
      importPreviewLinked: "students with an existing NIS will be linked",
      importConfirm: "Confirm Import"
    },
    studentDetail: {
      notFound: "Student data not found.",
      studentProfile: "Student Profile",
      profileDesc: "Detailed statistics and attendance history.",
      btnEdit: "Edit Data",
      btnSave: "Save Data",
      nameLabel: "Student Name",
      nisLabel: "Student ID (NIS)",
      genderLabel: "Gender",
      genderMale: "Male",
      genderFemale: "Female",
      genderUnset: "Not Set",
      phoneLabel: "Parent/Guardian Phone",
      phonePlaceholder: "e.g., 0812...",
      noteLabel: "Important Note",
      notePlaceholder: "e.g., Child has asthma...",
      tabStats: "Statistics",
      tabAttendance: "Attendance Log",
      tabGrades: "Grade History",
      statsAttendance: "Attendance Form",
      statsGrades: "Average Grade",
      gradeBook: "Gradebook",
      logStatus: "Status",
      logNote: "Note",
      logEmpty: "No attendance history yet.",
      gradeTitle: "Title",
      gradeScore: "Score",
      gradeEmpty: "No grades recorded yet.",
      successUpdate: "Student data successfully updated",
      attendanceFormat: "Format"
    },
    quizView: {
      question: "Question",
      of: "of",
      score: "Score",
      points: "pts",
      correct: "Correct",
      wrong: "Wrong",
      prev: "Previous",
      next: "Next",
      finish: "See Results",
      finishTitle: "Quiz Finished! 🎉",
      finalScore: "Final Score",
      totalCorrect: "Correct Answers",
      totalWrong: "Wrong Answers",
      totalQuestions: "Total Questions",
      reviewBtn: "Review Answers",
      backBtn: "Back to List",
      badgeInteractive: "Interactive Quiz",
      badgeNQuestions: "{{n}} Questions",
      noQuestions: "This quiz has no interactive multiple-choice questions.",
      noQuestionsHint: "Add answer options using the format: * Option A [*] to mark the correct answer.",
      templateBtn: "Insert Example Questions",
      startQuiz: "Start Quiz",
      answeredCorrectly: "Correct! +{{pts}} pts",
      answeredWrong: "Wrong. The correct answer is:",
      exitQuiz: "Exit Quiz",
      questionProgress: "Question {{current}} of {{total}}"
    },
    shortcuts: {
      desc_D: 'To Dashboard Page',
      desc_P: 'To Profile Page',
      desc_M: 'To Subjects Page',
      desc_C: 'To Classes Page',
      desc_S: 'To Students Page',
      desc_A: 'To Attendance Page',
      desc_G: 'To Gradebook Page',
      desc_N: 'To Teaching Materials Page',
      desc_J: 'To Teacher Journals Page',
      desc_E: 'To Evaluations Page',
      desc_T: 'To Calendar Page',
      desc_B: 'To Settings & Backup Page',
      desc_H: 'To Help/About Page'
    },
    about: {
      title: "About EduPlanner",
      desc: "EduPlanner is a lightweight school management information system that runs entirely in your browser. Designed to help teachers manage classes, students, attendance, and grades offline without needing to connect to an external server.",
      keyboardAccess: "Keyboard Accessibility",
      keyboardDesc: "EduPlanner is designed to be operated quickly using the keyboard. Below is a list of shortcuts you can use:",
      releaseStatus: "Public Beta",
      releaseStatusDesc: "A pre-release for evaluation and limited use with independent backups. It does not yet carry a stability guarantee.",
      version: "Version",
      revision: "Revision",
      devInfo: "Developer Information",
      devDesc: "This application is developed by",
      key: "Key",
      action: "Action"
    },
    settings: {
      title: "Settings & Backup",
      desc: "Manage your offline app data and appearance.",
      groupAppearance: "Appearance",
      groupBackup: "Backup / Restore",
      prefLang: "Language Preferences",
      prefTheme: "App Theme",
      themeLight: "Light",
      themeDark: "Dark",
      themeSystem: "System (Default)",
      notificationPrivacyLabel: "Notification Privacy",
      notificationPrivacyDescription: "By default, notifications hide class names, subjects, and times so they are not exposed on the lock screen. Enable details only on a protected personal device.",
      notificationDetailsHidden: "Details Hidden",
      notificationDetailsShown: "Details Shown",
      syncTitle: "Experimental Backup Provider",
      providerLabel: "Backup Provider",
      providerDisconnected: "Disconnected",
      providerMock: "Local Mock (Development Only)",
      disconnectedStatusTitle: "Provider disconnected",
      disconnectedStatusDesc: "No cloud backup is active. Use Download Backup to keep a copy outside this device.",
      mockStatusTitle: "Local simulation — not cloud backup",
      mockStatusDesc: "Mock mode stores a copy only in this browser's localStorage. Data is not sent to Google Drive or another cloud service and can be lost with browser data.",
      mockAutoBackup: "Local mock auto-backup (5 minutes)",
      statusActive: "Active",
      statusDisabled: "Disabled",
      mockBackupNow: "Create Mock Backup",
      mockBackingUp: "Creating...",
      mockRestore: "Restore Mock",
      mockRestoring: "Restoring...",
      mockBackupSuccess: "Local mock backup created. No data was uploaded to the cloud.",
      mockBackupError: "Failed to create local mock backup",
      mockRestoreEmpty: "No local mock backup is available to restore.",
      mockRestoreConfirm: "WARNING: Restoring the mock backup will overwrite all current data. Continue?",
      mockRestoreSuccess: "Data restored from the local mock backup.",
      mockRestoreError: "Failed to restore the local mock backup",
      importantTitle: "Important",
      importantDesc: "EduPlanner stores data **entirely in this browser** (IndexedDB). If you clear your browser's \"History/Cache\", this data may be lost. It is highly recommended to perform backups routinely.",
      exportTitle: "Export Data (Backup)",
      exportDesc: "Download all your data to a .json file",
      exportText: "Save this file on a flash drive, Google Drive, or email it to yourself as a backup.",
      importTitle: "Import Data (Restore)",
      importDesc: "Restore data from a .json backup file",
      importText: "Current data will be DELETED and completely replaced by data from the backup file.",
      btnExport: "Download Backup",
      btnImporting: "Importing...",
      btnImport: "Select Backup File",
      successExport: "Backup downloaded successfully",
      errorExport: "Failed to download backup",
      confirmImport: "WARNING: Importing data will overwrite all current data. Are you sure you want to proceed?",
      recoveryDownloaded: "A recovery snapshot of the current data has been downloaded.",
      recoveryConfirm: "Make sure the eduplanner_pre_restore recovery file is safely stored. Continue restoring and replace all current data?",
      recoveryCancelled: "Restore cancelled. The current database was not changed.",
      previewTitle: "Review Backup Restore",
      previewDescription: "Review the backup contents and status before replacing the local database.",
      previewSource: "Source",
      previewSourceCurrent: "Current format",
      previewSourceLegacy: "Legacy format",
      previewVersion: "Version migration",
      previewDatabaseVersion: "Database version",
      previewTotalRecords: "Total records",
      previewExportedAt: "Exported at",
      previewUnavailable: "Unavailable",
      previewIntegrity: "Integrity",
      previewIntegrityValid: "Valid",
      previewTableCounts: "Records per table",
      previewMigrationWarnings: "Legacy migration warnings",
      previewLegacyWarning: "The {{table}} table is unavailable in this legacy backup and will be initialized empty.",
      previewRecoveryCreated: "Recovery snapshot downloaded",
      previewConfirmReplace: "I understand that all current local data will be replaced after a recovery snapshot is created.",
      previewConfirmRecoverySaved: "I confirm that the recovery file is safely stored and approve replacing all current local data.",
      previewCancel: "Cancel",
      previewDownloadRecovery: "Download Recovery & Continue",
      previewPreparingRecovery: "Preparing recovery...",
      previewRestoreNow: "Restore Now",
      previewTableProfile: "Profile",
      previewTableSubjects: "Subjects",
      previewTableClasses: "Classes",
      previewTableStudents: "Students",
      previewTableAttendances: "Attendance",
      previewTableGrades: "Grades",
      previewTableNotes: "Notes & materials",
      previewTableTasks: "Tasks",
      previewTableTeachingSessions: "Teaching sessions",
      previewTableStudentNotes: "Student notes",
      previewTableSchedules: "Schedules",
      previewTableAcademicPeriods: "Academic Periods",
      previewTableClassEnrollments: "Class Enrollments",
      successImport: "Data imported successfully!",
      errorImport: "Invalid file format or an error occurred"
    },
    timeTracker: {
      btnStart: "Start Teaching",
      btnStop: "Stop",
      tooltipStop: "Stop and Save Teaching Time",
      title: "Time Tracker",
      desc: "Track your teaching time for this class.",
      selectClass: "Select Class *",
      selectClassPlaceholder: "Select Class...",
      selectSubject: "Subject (Optional)",
      selectSubjectPlaceholder: "All / General",
      general: "-- General --",
      startTimer: "Start Timer",
      errorNoClass: "Please select a class first!",
      successStart: "Started",
      successSave: "Teaching time recorded: {{minutes}} minutes",
      errorSave: "Failed to record teaching time"
    },
    common: {
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      add: "Add",
      close: "Close",
      success: "Success",
      error: "Error",
      loading: "Loading data...",
      empty: "No data available",
      search: "Search...",
      total: "Total",
      name: "Name",
      description: "Description",
      date: "Date",
      hour: "Hour",
      minute: "Minute",
      clear: "Clear"
    },
    securityImages: {
      externalTitle: "External image blocked",
      externalDescription: "Loading this image contacts a third-party site and reveals your device IP address.",
      loadExternal: "Load external image",
      blockedTitle: "This unsafe image source cannot be loaded"
    },
    scheduling: {
      tabSchedules: "Schedule",
      addSchedule: "Add Schedule",
      addDialogTitle: "Add Teaching Schedule",
      addDialogDesc: "Set up a recurring teaching schedule for this class.",
      editDialogTitle: "Edit Teaching Schedule",
      editDialogDesc: "Update recurring teaching schedule settings.",
      subjectLabel: "Subject",
      recurrenceLabel: "Recurrence",
      recurrenceDaily: "Daily",
      recurrenceWeekly: "Weekly",
      recurrenceMonthly: "Monthly",
      daysOfWeekLabel: "Days",
      startDateLabel: "Start Date",
      endCriteriaLabel: "End Criteria",
      endCriteriaCount: "Number of Recurrences (Count)",
      endCriteriaDate: "End Date",
      endCriteriaNone: "Forever / No Limit",
      countLabel: "Repeat (Times)",
      endDateLabel: "End Date",
      timeRangeLabel: "Teaching Time",
      startTimeLabel: "Start Time",
      endTimeLabel: "End Time",
      reminderLabel: "Notification Reminder",
      reminderOff: "Disabled",
      reminder5Min: "5 Minutes Before",
      reminder15Min: "15 Minutes Before",
      reminder30Min: "30 Minutes Before",
      reminder1Hour: "1 Hour Before",
      noSchedules: "No teaching schedules for this class yet.",
      createSchedulePrompt: "Start by adding a recurring teaching schedule to show classes on the Calendar and receive push notifications.",
      successAdd: "Schedule added successfully",
      errorIncomplete: "Please fill in the start time, end time, and start date.",
      errorSave: "Failed to save schedule!",
      successDelete: "Schedule deleted successfully",
      confirmDelete: "Delete this recurring teaching schedule?",
      notificationBanner: "Enable browser notifications to receive real-time class teaching schedule reminders.",
      btnEnableNotification: "Enable Reminders",
      notificationTitlePrivate: "EduPlanner Reminder",
      notificationTitle: "🔔 Class Starting Soon!",
      notificationBodyPrivate: "A teaching schedule reminder is available. Open EduPlanner to view the details.",
      notificationBody: "Class {{className}} ({{subjectName}}) is starting at {{startTime}}. Click to open teaching materials!",
      notificationBodyNoSubject: "Class {{className}} is starting at {{startTime}}. Click to open teaching materials!"
    }
  }
}
